### PR TITLE
jeevan.txt file has been modified

### PR DESCRIPTION
**Pull request by jeevanpoudel**
mie name is khan

### CODE REVIEW

**Comment by henishgurung15** [comment]
jiwan yo baehna

**Comment by AmunTimilsina** [comment]
its good .. i like this project

**Comment by Rishan99** [comment]
khattam cha

**Comment by AmunTimilsina** [comment]
last alxi lagyo yrrrrrr

**Comment by henishgurung15** [comment]
maja ako cha hai???
👍

**Comment by henishgurung15** [comment]
💯

**Comment by AmunTimilsina** [comment]
i accept this project... yo project le $10000000000 kamauxa

**Comment by jeevanpoudel** [comment]
amun tmle malai kati rupee dina x re

**Pull request merged**
